// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: substrait/proto/extended_expression.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_substrait_2fproto_2fextended_5fexpression_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_substrait_2fproto_2fextended_5fexpression_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "substrait/proto/algebra.pb.h"
#include "substrait/proto/extensions/extensions.pb.h"
#include "substrait/proto/plan.pb.h"
#include "substrait/proto/type.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_substrait_2fproto_2fextended_5fexpression_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_substrait_2fproto_2fextended_5fexpression_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_substrait_2fproto_2fextended_5fexpression_2eproto;
namespace substrait {
namespace proto {
class ExpressionReference;
class ExpressionReferenceDefaultTypeInternal;
extern ExpressionReferenceDefaultTypeInternal _ExpressionReference_default_instance_;
class ExtendedExpression;
class ExtendedExpressionDefaultTypeInternal;
extern ExtendedExpressionDefaultTypeInternal _ExtendedExpression_default_instance_;
}  // namespace proto
}  // namespace substrait
PROTOBUF_NAMESPACE_OPEN
template<> ::substrait::proto::ExpressionReference* Arena::CreateMaybeMessage<::substrait::proto::ExpressionReference>(Arena*);
template<> ::substrait::proto::ExtendedExpression* Arena::CreateMaybeMessage<::substrait::proto::ExtendedExpression>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace substrait {
namespace proto {

// ===================================================================

class ExpressionReference PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:substrait.proto.ExpressionReference) */ {
 public:
  inline ExpressionReference() : ExpressionReference(nullptr) {};
  virtual ~ExpressionReference();

  ExpressionReference(const ExpressionReference& from);
  ExpressionReference(ExpressionReference&& from) noexcept
    : ExpressionReference() {
    *this = ::std::move(from);
  }

  inline ExpressionReference& operator=(const ExpressionReference& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExpressionReference& operator=(ExpressionReference&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ExpressionReference& default_instance();

  enum ExprTypeCase {
    kExpression = 1,
    kMeasure = 2,
    EXPR_TYPE_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ExpressionReference* internal_default_instance() {
    return reinterpret_cast<const ExpressionReference*>(
               &_ExpressionReference_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ExpressionReference& a, ExpressionReference& b) {
    a.Swap(&b);
  }
  inline void Swap(ExpressionReference* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExpressionReference* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ExpressionReference* New() const final {
    return CreateMaybeMessage<ExpressionReference>(nullptr);
  }

  ExpressionReference* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ExpressionReference>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ExpressionReference& from);
  void MergeFrom(const ExpressionReference& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ExpressionReference* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "substrait.proto.ExpressionReference";
  }
  protected:
  explicit ExpressionReference(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_substrait_2fproto_2fextended_5fexpression_2eproto);
    return ::descriptor_table_substrait_2fproto_2fextended_5fexpression_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOutputNamesFieldNumber = 3,
    kExpressionFieldNumber = 1,
    kMeasureFieldNumber = 2,
  };
  // repeated string output_names = 3;
  int output_names_size() const;
  private:
  int _internal_output_names_size() const;
  public:
  void clear_output_names();
  const std::string& output_names(int index) const;
  std::string* mutable_output_names(int index);
  void set_output_names(int index, const std::string& value);
  void set_output_names(int index, std::string&& value);
  void set_output_names(int index, const char* value);
  void set_output_names(int index, const char* value, size_t size);
  std::string* add_output_names();
  void add_output_names(const std::string& value);
  void add_output_names(std::string&& value);
  void add_output_names(const char* value);
  void add_output_names(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& output_names() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_output_names();
  private:
  const std::string& _internal_output_names(int index) const;
  std::string* _internal_add_output_names();
  public:

  // .substrait.proto.Expression expression = 1;
  bool has_expression() const;
  private:
  bool _internal_has_expression() const;
  public:
  void clear_expression();
  const ::substrait::proto::Expression& expression() const;
  ::substrait::proto::Expression* release_expression();
  ::substrait::proto::Expression* mutable_expression();
  void set_allocated_expression(::substrait::proto::Expression* expression);
  private:
  const ::substrait::proto::Expression& _internal_expression() const;
  ::substrait::proto::Expression* _internal_mutable_expression();
  public:
  void unsafe_arena_set_allocated_expression(
      ::substrait::proto::Expression* expression);
  ::substrait::proto::Expression* unsafe_arena_release_expression();

  // .substrait.proto.AggregateFunction measure = 2;
  bool has_measure() const;
  private:
  bool _internal_has_measure() const;
  public:
  void clear_measure();
  const ::substrait::proto::AggregateFunction& measure() const;
  ::substrait::proto::AggregateFunction* release_measure();
  ::substrait::proto::AggregateFunction* mutable_measure();
  void set_allocated_measure(::substrait::proto::AggregateFunction* measure);
  private:
  const ::substrait::proto::AggregateFunction& _internal_measure() const;
  ::substrait::proto::AggregateFunction* _internal_mutable_measure();
  public:
  void unsafe_arena_set_allocated_measure(
      ::substrait::proto::AggregateFunction* measure);
  ::substrait::proto::AggregateFunction* unsafe_arena_release_measure();

  void clear_expr_type();
  ExprTypeCase expr_type_case() const;
  // @@protoc_insertion_point(class_scope:substrait.proto.ExpressionReference)
 private:
  class _Internal;
  void set_has_expression();
  void set_has_measure();

  inline bool has_expr_type() const;
  inline void clear_has_expr_type();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> output_names_;
  union ExprTypeUnion {
    ExprTypeUnion() {}
    ::substrait::proto::Expression* expression_;
    ::substrait::proto::AggregateFunction* measure_;
  } expr_type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_substrait_2fproto_2fextended_5fexpression_2eproto;
};
// -------------------------------------------------------------------

class ExtendedExpression PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:substrait.proto.ExtendedExpression) */ {
 public:
  inline ExtendedExpression() : ExtendedExpression(nullptr) {};
  virtual ~ExtendedExpression();

  ExtendedExpression(const ExtendedExpression& from);
  ExtendedExpression(ExtendedExpression&& from) noexcept
    : ExtendedExpression() {
    *this = ::std::move(from);
  }

  inline ExtendedExpression& operator=(const ExtendedExpression& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExtendedExpression& operator=(ExtendedExpression&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ExtendedExpression& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ExtendedExpression* internal_default_instance() {
    return reinterpret_cast<const ExtendedExpression*>(
               &_ExtendedExpression_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ExtendedExpression& a, ExtendedExpression& b) {
    a.Swap(&b);
  }
  inline void Swap(ExtendedExpression* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExtendedExpression* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ExtendedExpression* New() const final {
    return CreateMaybeMessage<ExtendedExpression>(nullptr);
  }

  ExtendedExpression* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ExtendedExpression>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ExtendedExpression& from);
  void MergeFrom(const ExtendedExpression& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ExtendedExpression* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "substrait.proto.ExtendedExpression";
  }
  protected:
  explicit ExtendedExpression(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_substrait_2fproto_2fextended_5fexpression_2eproto);
    return ::descriptor_table_substrait_2fproto_2fextended_5fexpression_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kExtensionUrisFieldNumber = 1,
    kExtensionsFieldNumber = 2,
    kReferredExprFieldNumber = 3,
    kExpectedTypeUrlsFieldNumber = 6,
    kBaseSchemaFieldNumber = 4,
    kAdvancedExtensionsFieldNumber = 5,
    kVersionFieldNumber = 7,
  };
  // repeated .substrait.proto.extensions.SimpleExtensionURI extension_uris = 1;
  int extension_uris_size() const;
  private:
  int _internal_extension_uris_size() const;
  public:
  void clear_extension_uris();
  ::substrait::proto::extensions::SimpleExtensionURI* mutable_extension_uris(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::extensions::SimpleExtensionURI >*
      mutable_extension_uris();
  private:
  const ::substrait::proto::extensions::SimpleExtensionURI& _internal_extension_uris(int index) const;
  ::substrait::proto::extensions::SimpleExtensionURI* _internal_add_extension_uris();
  public:
  const ::substrait::proto::extensions::SimpleExtensionURI& extension_uris(int index) const;
  ::substrait::proto::extensions::SimpleExtensionURI* add_extension_uris();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::extensions::SimpleExtensionURI >&
      extension_uris() const;

  // repeated .substrait.proto.extensions.SimpleExtensionDeclaration extensions = 2;
  int extensions_size() const;
  private:
  int _internal_extensions_size() const;
  public:
  void clear_extensions();
  ::substrait::proto::extensions::SimpleExtensionDeclaration* mutable_extensions(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::extensions::SimpleExtensionDeclaration >*
      mutable_extensions();
  private:
  const ::substrait::proto::extensions::SimpleExtensionDeclaration& _internal_extensions(int index) const;
  ::substrait::proto::extensions::SimpleExtensionDeclaration* _internal_add_extensions();
  public:
  const ::substrait::proto::extensions::SimpleExtensionDeclaration& extensions(int index) const;
  ::substrait::proto::extensions::SimpleExtensionDeclaration* add_extensions();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::extensions::SimpleExtensionDeclaration >&
      extensions() const;

  // repeated .substrait.proto.ExpressionReference referred_expr = 3;
  int referred_expr_size() const;
  private:
  int _internal_referred_expr_size() const;
  public:
  void clear_referred_expr();
  ::substrait::proto::ExpressionReference* mutable_referred_expr(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::ExpressionReference >*
      mutable_referred_expr();
  private:
  const ::substrait::proto::ExpressionReference& _internal_referred_expr(int index) const;
  ::substrait::proto::ExpressionReference* _internal_add_referred_expr();
  public:
  const ::substrait::proto::ExpressionReference& referred_expr(int index) const;
  ::substrait::proto::ExpressionReference* add_referred_expr();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::ExpressionReference >&
      referred_expr() const;

  // repeated string expected_type_urls = 6;
  int expected_type_urls_size() const;
  private:
  int _internal_expected_type_urls_size() const;
  public:
  void clear_expected_type_urls();
  const std::string& expected_type_urls(int index) const;
  std::string* mutable_expected_type_urls(int index);
  void set_expected_type_urls(int index, const std::string& value);
  void set_expected_type_urls(int index, std::string&& value);
  void set_expected_type_urls(int index, const char* value);
  void set_expected_type_urls(int index, const char* value, size_t size);
  std::string* add_expected_type_urls();
  void add_expected_type_urls(const std::string& value);
  void add_expected_type_urls(std::string&& value);
  void add_expected_type_urls(const char* value);
  void add_expected_type_urls(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& expected_type_urls() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_expected_type_urls();
  private:
  const std::string& _internal_expected_type_urls(int index) const;
  std::string* _internal_add_expected_type_urls();
  public:

  // .substrait.proto.NamedStruct base_schema = 4;
  bool has_base_schema() const;
  private:
  bool _internal_has_base_schema() const;
  public:
  void clear_base_schema();
  const ::substrait::proto::NamedStruct& base_schema() const;
  ::substrait::proto::NamedStruct* release_base_schema();
  ::substrait::proto::NamedStruct* mutable_base_schema();
  void set_allocated_base_schema(::substrait::proto::NamedStruct* base_schema);
  private:
  const ::substrait::proto::NamedStruct& _internal_base_schema() const;
  ::substrait::proto::NamedStruct* _internal_mutable_base_schema();
  public:
  void unsafe_arena_set_allocated_base_schema(
      ::substrait::proto::NamedStruct* base_schema);
  ::substrait::proto::NamedStruct* unsafe_arena_release_base_schema();

  // .substrait.proto.extensions.AdvancedExtension advanced_extensions = 5;
  bool has_advanced_extensions() const;
  private:
  bool _internal_has_advanced_extensions() const;
  public:
  void clear_advanced_extensions();
  const ::substrait::proto::extensions::AdvancedExtension& advanced_extensions() const;
  ::substrait::proto::extensions::AdvancedExtension* release_advanced_extensions();
  ::substrait::proto::extensions::AdvancedExtension* mutable_advanced_extensions();
  void set_allocated_advanced_extensions(::substrait::proto::extensions::AdvancedExtension* advanced_extensions);
  private:
  const ::substrait::proto::extensions::AdvancedExtension& _internal_advanced_extensions() const;
  ::substrait::proto::extensions::AdvancedExtension* _internal_mutable_advanced_extensions();
  public:
  void unsafe_arena_set_allocated_advanced_extensions(
      ::substrait::proto::extensions::AdvancedExtension* advanced_extensions);
  ::substrait::proto::extensions::AdvancedExtension* unsafe_arena_release_advanced_extensions();

  // .substrait.proto.Version version = 7;
  bool has_version() const;
  private:
  bool _internal_has_version() const;
  public:
  void clear_version();
  const ::substrait::proto::Version& version() const;
  ::substrait::proto::Version* release_version();
  ::substrait::proto::Version* mutable_version();
  void set_allocated_version(::substrait::proto::Version* version);
  private:
  const ::substrait::proto::Version& _internal_version() const;
  ::substrait::proto::Version* _internal_mutable_version();
  public:
  void unsafe_arena_set_allocated_version(
      ::substrait::proto::Version* version);
  ::substrait::proto::Version* unsafe_arena_release_version();

  // @@protoc_insertion_point(class_scope:substrait.proto.ExtendedExpression)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::extensions::SimpleExtensionURI > extension_uris_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::extensions::SimpleExtensionDeclaration > extensions_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::ExpressionReference > referred_expr_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> expected_type_urls_;
  ::substrait::proto::NamedStruct* base_schema_;
  ::substrait::proto::extensions::AdvancedExtension* advanced_extensions_;
  ::substrait::proto::Version* version_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_substrait_2fproto_2fextended_5fexpression_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ExpressionReference

// .substrait.proto.Expression expression = 1;
inline bool ExpressionReference::_internal_has_expression() const {
  return expr_type_case() == kExpression;
}
inline bool ExpressionReference::has_expression() const {
  return _internal_has_expression();
}
inline void ExpressionReference::set_has_expression() {
  _oneof_case_[0] = kExpression;
}
inline ::substrait::proto::Expression* ExpressionReference::release_expression() {
  // @@protoc_insertion_point(field_release:substrait.proto.ExpressionReference.expression)
  if (_internal_has_expression()) {
    clear_has_expr_type();
      ::substrait::proto::Expression* temp = expr_type_.expression_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    expr_type_.expression_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::substrait::proto::Expression& ExpressionReference::_internal_expression() const {
  return _internal_has_expression()
      ? *expr_type_.expression_
      : *reinterpret_cast< ::substrait::proto::Expression*>(&::substrait::proto::_Expression_default_instance_);
}
inline const ::substrait::proto::Expression& ExpressionReference::expression() const {
  // @@protoc_insertion_point(field_get:substrait.proto.ExpressionReference.expression)
  return _internal_expression();
}
inline ::substrait::proto::Expression* ExpressionReference::unsafe_arena_release_expression() {
  // @@protoc_insertion_point(field_unsafe_arena_release:substrait.proto.ExpressionReference.expression)
  if (_internal_has_expression()) {
    clear_has_expr_type();
    ::substrait::proto::Expression* temp = expr_type_.expression_;
    expr_type_.expression_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ExpressionReference::unsafe_arena_set_allocated_expression(::substrait::proto::Expression* expression) {
  clear_expr_type();
  if (expression) {
    set_has_expression();
    expr_type_.expression_ = expression;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:substrait.proto.ExpressionReference.expression)
}
inline ::substrait::proto::Expression* ExpressionReference::_internal_mutable_expression() {
  if (!_internal_has_expression()) {
    clear_expr_type();
    set_has_expression();
    expr_type_.expression_ = CreateMaybeMessage< ::substrait::proto::Expression >(GetArena());
  }
  return expr_type_.expression_;
}
inline ::substrait::proto::Expression* ExpressionReference::mutable_expression() {
  // @@protoc_insertion_point(field_mutable:substrait.proto.ExpressionReference.expression)
  return _internal_mutable_expression();
}

// .substrait.proto.AggregateFunction measure = 2;
inline bool ExpressionReference::_internal_has_measure() const {
  return expr_type_case() == kMeasure;
}
inline bool ExpressionReference::has_measure() const {
  return _internal_has_measure();
}
inline void ExpressionReference::set_has_measure() {
  _oneof_case_[0] = kMeasure;
}
inline ::substrait::proto::AggregateFunction* ExpressionReference::release_measure() {
  // @@protoc_insertion_point(field_release:substrait.proto.ExpressionReference.measure)
  if (_internal_has_measure()) {
    clear_has_expr_type();
      ::substrait::proto::AggregateFunction* temp = expr_type_.measure_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    expr_type_.measure_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::substrait::proto::AggregateFunction& ExpressionReference::_internal_measure() const {
  return _internal_has_measure()
      ? *expr_type_.measure_
      : *reinterpret_cast< ::substrait::proto::AggregateFunction*>(&::substrait::proto::_AggregateFunction_default_instance_);
}
inline const ::substrait::proto::AggregateFunction& ExpressionReference::measure() const {
  // @@protoc_insertion_point(field_get:substrait.proto.ExpressionReference.measure)
  return _internal_measure();
}
inline ::substrait::proto::AggregateFunction* ExpressionReference::unsafe_arena_release_measure() {
  // @@protoc_insertion_point(field_unsafe_arena_release:substrait.proto.ExpressionReference.measure)
  if (_internal_has_measure()) {
    clear_has_expr_type();
    ::substrait::proto::AggregateFunction* temp = expr_type_.measure_;
    expr_type_.measure_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ExpressionReference::unsafe_arena_set_allocated_measure(::substrait::proto::AggregateFunction* measure) {
  clear_expr_type();
  if (measure) {
    set_has_measure();
    expr_type_.measure_ = measure;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:substrait.proto.ExpressionReference.measure)
}
inline ::substrait::proto::AggregateFunction* ExpressionReference::_internal_mutable_measure() {
  if (!_internal_has_measure()) {
    clear_expr_type();
    set_has_measure();
    expr_type_.measure_ = CreateMaybeMessage< ::substrait::proto::AggregateFunction >(GetArena());
  }
  return expr_type_.measure_;
}
inline ::substrait::proto::AggregateFunction* ExpressionReference::mutable_measure() {
  // @@protoc_insertion_point(field_mutable:substrait.proto.ExpressionReference.measure)
  return _internal_mutable_measure();
}

// repeated string output_names = 3;
inline int ExpressionReference::_internal_output_names_size() const {
  return output_names_.size();
}
inline int ExpressionReference::output_names_size() const {
  return _internal_output_names_size();
}
inline void ExpressionReference::clear_output_names() {
  output_names_.Clear();
}
inline std::string* ExpressionReference::add_output_names() {
  // @@protoc_insertion_point(field_add_mutable:substrait.proto.ExpressionReference.output_names)
  return _internal_add_output_names();
}
inline const std::string& ExpressionReference::_internal_output_names(int index) const {
  return output_names_.Get(index);
}
inline const std::string& ExpressionReference::output_names(int index) const {
  // @@protoc_insertion_point(field_get:substrait.proto.ExpressionReference.output_names)
  return _internal_output_names(index);
}
inline std::string* ExpressionReference::mutable_output_names(int index) {
  // @@protoc_insertion_point(field_mutable:substrait.proto.ExpressionReference.output_names)
  return output_names_.Mutable(index);
}
inline void ExpressionReference::set_output_names(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:substrait.proto.ExpressionReference.output_names)
  output_names_.Mutable(index)->assign(value);
}
inline void ExpressionReference::set_output_names(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:substrait.proto.ExpressionReference.output_names)
  output_names_.Mutable(index)->assign(std::move(value));
}
inline void ExpressionReference::set_output_names(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  output_names_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:substrait.proto.ExpressionReference.output_names)
}
inline void ExpressionReference::set_output_names(int index, const char* value, size_t size) {
  output_names_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:substrait.proto.ExpressionReference.output_names)
}
inline std::string* ExpressionReference::_internal_add_output_names() {
  return output_names_.Add();
}
inline void ExpressionReference::add_output_names(const std::string& value) {
  output_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:substrait.proto.ExpressionReference.output_names)
}
inline void ExpressionReference::add_output_names(std::string&& value) {
  output_names_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:substrait.proto.ExpressionReference.output_names)
}
inline void ExpressionReference::add_output_names(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  output_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:substrait.proto.ExpressionReference.output_names)
}
inline void ExpressionReference::add_output_names(const char* value, size_t size) {
  output_names_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:substrait.proto.ExpressionReference.output_names)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
ExpressionReference::output_names() const {
  // @@protoc_insertion_point(field_list:substrait.proto.ExpressionReference.output_names)
  return output_names_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
ExpressionReference::mutable_output_names() {
  // @@protoc_insertion_point(field_mutable_list:substrait.proto.ExpressionReference.output_names)
  return &output_names_;
}

inline bool ExpressionReference::has_expr_type() const {
  return expr_type_case() != EXPR_TYPE_NOT_SET;
}
inline void ExpressionReference::clear_has_expr_type() {
  _oneof_case_[0] = EXPR_TYPE_NOT_SET;
}
inline ExpressionReference::ExprTypeCase ExpressionReference::expr_type_case() const {
  return ExpressionReference::ExprTypeCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// ExtendedExpression

// .substrait.proto.Version version = 7;
inline bool ExtendedExpression::_internal_has_version() const {
  return this != internal_default_instance() && version_ != nullptr;
}
inline bool ExtendedExpression::has_version() const {
  return _internal_has_version();
}
inline const ::substrait::proto::Version& ExtendedExpression::_internal_version() const {
  const ::substrait::proto::Version* p = version_;
  return p != nullptr ? *p : *reinterpret_cast<const ::substrait::proto::Version*>(
      &::substrait::proto::_Version_default_instance_);
}
inline const ::substrait::proto::Version& ExtendedExpression::version() const {
  // @@protoc_insertion_point(field_get:substrait.proto.ExtendedExpression.version)
  return _internal_version();
}
inline void ExtendedExpression::unsafe_arena_set_allocated_version(
    ::substrait::proto::Version* version) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(version_);
  }
  version_ = version;
  if (version) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:substrait.proto.ExtendedExpression.version)
}
inline ::substrait::proto::Version* ExtendedExpression::release_version() {
  auto temp = unsafe_arena_release_version();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::substrait::proto::Version* ExtendedExpression::unsafe_arena_release_version() {
  // @@protoc_insertion_point(field_release:substrait.proto.ExtendedExpression.version)
  
  ::substrait::proto::Version* temp = version_;
  version_ = nullptr;
  return temp;
}
inline ::substrait::proto::Version* ExtendedExpression::_internal_mutable_version() {
  
  if (version_ == nullptr) {
    auto* p = CreateMaybeMessage<::substrait::proto::Version>(GetArena());
    version_ = p;
  }
  return version_;
}
inline ::substrait::proto::Version* ExtendedExpression::mutable_version() {
  // @@protoc_insertion_point(field_mutable:substrait.proto.ExtendedExpression.version)
  return _internal_mutable_version();
}
inline void ExtendedExpression::set_allocated_version(::substrait::proto::Version* version) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(version_);
  }
  if (version) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(version)->GetArena();
    if (message_arena != submessage_arena) {
      version = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, version, submessage_arena);
    }
    
  } else {
    
  }
  version_ = version;
  // @@protoc_insertion_point(field_set_allocated:substrait.proto.ExtendedExpression.version)
}

// repeated .substrait.proto.extensions.SimpleExtensionURI extension_uris = 1;
inline int ExtendedExpression::_internal_extension_uris_size() const {
  return extension_uris_.size();
}
inline int ExtendedExpression::extension_uris_size() const {
  return _internal_extension_uris_size();
}
inline ::substrait::proto::extensions::SimpleExtensionURI* ExtendedExpression::mutable_extension_uris(int index) {
  // @@protoc_insertion_point(field_mutable:substrait.proto.ExtendedExpression.extension_uris)
  return extension_uris_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::extensions::SimpleExtensionURI >*
ExtendedExpression::mutable_extension_uris() {
  // @@protoc_insertion_point(field_mutable_list:substrait.proto.ExtendedExpression.extension_uris)
  return &extension_uris_;
}
inline const ::substrait::proto::extensions::SimpleExtensionURI& ExtendedExpression::_internal_extension_uris(int index) const {
  return extension_uris_.Get(index);
}
inline const ::substrait::proto::extensions::SimpleExtensionURI& ExtendedExpression::extension_uris(int index) const {
  // @@protoc_insertion_point(field_get:substrait.proto.ExtendedExpression.extension_uris)
  return _internal_extension_uris(index);
}
inline ::substrait::proto::extensions::SimpleExtensionURI* ExtendedExpression::_internal_add_extension_uris() {
  return extension_uris_.Add();
}
inline ::substrait::proto::extensions::SimpleExtensionURI* ExtendedExpression::add_extension_uris() {
  // @@protoc_insertion_point(field_add:substrait.proto.ExtendedExpression.extension_uris)
  return _internal_add_extension_uris();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::extensions::SimpleExtensionURI >&
ExtendedExpression::extension_uris() const {
  // @@protoc_insertion_point(field_list:substrait.proto.ExtendedExpression.extension_uris)
  return extension_uris_;
}

// repeated .substrait.proto.extensions.SimpleExtensionDeclaration extensions = 2;
inline int ExtendedExpression::_internal_extensions_size() const {
  return extensions_.size();
}
inline int ExtendedExpression::extensions_size() const {
  return _internal_extensions_size();
}
inline ::substrait::proto::extensions::SimpleExtensionDeclaration* ExtendedExpression::mutable_extensions(int index) {
  // @@protoc_insertion_point(field_mutable:substrait.proto.ExtendedExpression.extensions)
  return extensions_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::extensions::SimpleExtensionDeclaration >*
ExtendedExpression::mutable_extensions() {
  // @@protoc_insertion_point(field_mutable_list:substrait.proto.ExtendedExpression.extensions)
  return &extensions_;
}
inline const ::substrait::proto::extensions::SimpleExtensionDeclaration& ExtendedExpression::_internal_extensions(int index) const {
  return extensions_.Get(index);
}
inline const ::substrait::proto::extensions::SimpleExtensionDeclaration& ExtendedExpression::extensions(int index) const {
  // @@protoc_insertion_point(field_get:substrait.proto.ExtendedExpression.extensions)
  return _internal_extensions(index);
}
inline ::substrait::proto::extensions::SimpleExtensionDeclaration* ExtendedExpression::_internal_add_extensions() {
  return extensions_.Add();
}
inline ::substrait::proto::extensions::SimpleExtensionDeclaration* ExtendedExpression::add_extensions() {
  // @@protoc_insertion_point(field_add:substrait.proto.ExtendedExpression.extensions)
  return _internal_add_extensions();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::extensions::SimpleExtensionDeclaration >&
ExtendedExpression::extensions() const {
  // @@protoc_insertion_point(field_list:substrait.proto.ExtendedExpression.extensions)
  return extensions_;
}

// repeated .substrait.proto.ExpressionReference referred_expr = 3;
inline int ExtendedExpression::_internal_referred_expr_size() const {
  return referred_expr_.size();
}
inline int ExtendedExpression::referred_expr_size() const {
  return _internal_referred_expr_size();
}
inline void ExtendedExpression::clear_referred_expr() {
  referred_expr_.Clear();
}
inline ::substrait::proto::ExpressionReference* ExtendedExpression::mutable_referred_expr(int index) {
  // @@protoc_insertion_point(field_mutable:substrait.proto.ExtendedExpression.referred_expr)
  return referred_expr_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::ExpressionReference >*
ExtendedExpression::mutable_referred_expr() {
  // @@protoc_insertion_point(field_mutable_list:substrait.proto.ExtendedExpression.referred_expr)
  return &referred_expr_;
}
inline const ::substrait::proto::ExpressionReference& ExtendedExpression::_internal_referred_expr(int index) const {
  return referred_expr_.Get(index);
}
inline const ::substrait::proto::ExpressionReference& ExtendedExpression::referred_expr(int index) const {
  // @@protoc_insertion_point(field_get:substrait.proto.ExtendedExpression.referred_expr)
  return _internal_referred_expr(index);
}
inline ::substrait::proto::ExpressionReference* ExtendedExpression::_internal_add_referred_expr() {
  return referred_expr_.Add();
}
inline ::substrait::proto::ExpressionReference* ExtendedExpression::add_referred_expr() {
  // @@protoc_insertion_point(field_add:substrait.proto.ExtendedExpression.referred_expr)
  return _internal_add_referred_expr();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::ExpressionReference >&
ExtendedExpression::referred_expr() const {
  // @@protoc_insertion_point(field_list:substrait.proto.ExtendedExpression.referred_expr)
  return referred_expr_;
}

// .substrait.proto.NamedStruct base_schema = 4;
inline bool ExtendedExpression::_internal_has_base_schema() const {
  return this != internal_default_instance() && base_schema_ != nullptr;
}
inline bool ExtendedExpression::has_base_schema() const {
  return _internal_has_base_schema();
}
inline const ::substrait::proto::NamedStruct& ExtendedExpression::_internal_base_schema() const {
  const ::substrait::proto::NamedStruct* p = base_schema_;
  return p != nullptr ? *p : *reinterpret_cast<const ::substrait::proto::NamedStruct*>(
      &::substrait::proto::_NamedStruct_default_instance_);
}
inline const ::substrait::proto::NamedStruct& ExtendedExpression::base_schema() const {
  // @@protoc_insertion_point(field_get:substrait.proto.ExtendedExpression.base_schema)
  return _internal_base_schema();
}
inline void ExtendedExpression::unsafe_arena_set_allocated_base_schema(
    ::substrait::proto::NamedStruct* base_schema) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(base_schema_);
  }
  base_schema_ = base_schema;
  if (base_schema) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:substrait.proto.ExtendedExpression.base_schema)
}
inline ::substrait::proto::NamedStruct* ExtendedExpression::release_base_schema() {
  auto temp = unsafe_arena_release_base_schema();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::substrait::proto::NamedStruct* ExtendedExpression::unsafe_arena_release_base_schema() {
  // @@protoc_insertion_point(field_release:substrait.proto.ExtendedExpression.base_schema)
  
  ::substrait::proto::NamedStruct* temp = base_schema_;
  base_schema_ = nullptr;
  return temp;
}
inline ::substrait::proto::NamedStruct* ExtendedExpression::_internal_mutable_base_schema() {
  
  if (base_schema_ == nullptr) {
    auto* p = CreateMaybeMessage<::substrait::proto::NamedStruct>(GetArena());
    base_schema_ = p;
  }
  return base_schema_;
}
inline ::substrait::proto::NamedStruct* ExtendedExpression::mutable_base_schema() {
  // @@protoc_insertion_point(field_mutable:substrait.proto.ExtendedExpression.base_schema)
  return _internal_mutable_base_schema();
}
inline void ExtendedExpression::set_allocated_base_schema(::substrait::proto::NamedStruct* base_schema) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(base_schema_);
  }
  if (base_schema) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(base_schema)->GetArena();
    if (message_arena != submessage_arena) {
      base_schema = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, base_schema, submessage_arena);
    }
    
  } else {
    
  }
  base_schema_ = base_schema;
  // @@protoc_insertion_point(field_set_allocated:substrait.proto.ExtendedExpression.base_schema)
}

// .substrait.proto.extensions.AdvancedExtension advanced_extensions = 5;
inline bool ExtendedExpression::_internal_has_advanced_extensions() const {
  return this != internal_default_instance() && advanced_extensions_ != nullptr;
}
inline bool ExtendedExpression::has_advanced_extensions() const {
  return _internal_has_advanced_extensions();
}
inline const ::substrait::proto::extensions::AdvancedExtension& ExtendedExpression::_internal_advanced_extensions() const {
  const ::substrait::proto::extensions::AdvancedExtension* p = advanced_extensions_;
  return p != nullptr ? *p : *reinterpret_cast<const ::substrait::proto::extensions::AdvancedExtension*>(
      &::substrait::proto::extensions::_AdvancedExtension_default_instance_);
}
inline const ::substrait::proto::extensions::AdvancedExtension& ExtendedExpression::advanced_extensions() const {
  // @@protoc_insertion_point(field_get:substrait.proto.ExtendedExpression.advanced_extensions)
  return _internal_advanced_extensions();
}
inline void ExtendedExpression::unsafe_arena_set_allocated_advanced_extensions(
    ::substrait::proto::extensions::AdvancedExtension* advanced_extensions) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(advanced_extensions_);
  }
  advanced_extensions_ = advanced_extensions;
  if (advanced_extensions) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:substrait.proto.ExtendedExpression.advanced_extensions)
}
inline ::substrait::proto::extensions::AdvancedExtension* ExtendedExpression::release_advanced_extensions() {
  auto temp = unsafe_arena_release_advanced_extensions();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::substrait::proto::extensions::AdvancedExtension* ExtendedExpression::unsafe_arena_release_advanced_extensions() {
  // @@protoc_insertion_point(field_release:substrait.proto.ExtendedExpression.advanced_extensions)
  
  ::substrait::proto::extensions::AdvancedExtension* temp = advanced_extensions_;
  advanced_extensions_ = nullptr;
  return temp;
}
inline ::substrait::proto::extensions::AdvancedExtension* ExtendedExpression::_internal_mutable_advanced_extensions() {
  
  if (advanced_extensions_ == nullptr) {
    auto* p = CreateMaybeMessage<::substrait::proto::extensions::AdvancedExtension>(GetArena());
    advanced_extensions_ = p;
  }
  return advanced_extensions_;
}
inline ::substrait::proto::extensions::AdvancedExtension* ExtendedExpression::mutable_advanced_extensions() {
  // @@protoc_insertion_point(field_mutable:substrait.proto.ExtendedExpression.advanced_extensions)
  return _internal_mutable_advanced_extensions();
}
inline void ExtendedExpression::set_allocated_advanced_extensions(::substrait::proto::extensions::AdvancedExtension* advanced_extensions) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(advanced_extensions_);
  }
  if (advanced_extensions) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(advanced_extensions)->GetArena();
    if (message_arena != submessage_arena) {
      advanced_extensions = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, advanced_extensions, submessage_arena);
    }
    
  } else {
    
  }
  advanced_extensions_ = advanced_extensions;
  // @@protoc_insertion_point(field_set_allocated:substrait.proto.ExtendedExpression.advanced_extensions)
}

// repeated string expected_type_urls = 6;
inline int ExtendedExpression::_internal_expected_type_urls_size() const {
  return expected_type_urls_.size();
}
inline int ExtendedExpression::expected_type_urls_size() const {
  return _internal_expected_type_urls_size();
}
inline void ExtendedExpression::clear_expected_type_urls() {
  expected_type_urls_.Clear();
}
inline std::string* ExtendedExpression::add_expected_type_urls() {
  // @@protoc_insertion_point(field_add_mutable:substrait.proto.ExtendedExpression.expected_type_urls)
  return _internal_add_expected_type_urls();
}
inline const std::string& ExtendedExpression::_internal_expected_type_urls(int index) const {
  return expected_type_urls_.Get(index);
}
inline const std::string& ExtendedExpression::expected_type_urls(int index) const {
  // @@protoc_insertion_point(field_get:substrait.proto.ExtendedExpression.expected_type_urls)
  return _internal_expected_type_urls(index);
}
inline std::string* ExtendedExpression::mutable_expected_type_urls(int index) {
  // @@protoc_insertion_point(field_mutable:substrait.proto.ExtendedExpression.expected_type_urls)
  return expected_type_urls_.Mutable(index);
}
inline void ExtendedExpression::set_expected_type_urls(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:substrait.proto.ExtendedExpression.expected_type_urls)
  expected_type_urls_.Mutable(index)->assign(value);
}
inline void ExtendedExpression::set_expected_type_urls(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:substrait.proto.ExtendedExpression.expected_type_urls)
  expected_type_urls_.Mutable(index)->assign(std::move(value));
}
inline void ExtendedExpression::set_expected_type_urls(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  expected_type_urls_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:substrait.proto.ExtendedExpression.expected_type_urls)
}
inline void ExtendedExpression::set_expected_type_urls(int index, const char* value, size_t size) {
  expected_type_urls_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:substrait.proto.ExtendedExpression.expected_type_urls)
}
inline std::string* ExtendedExpression::_internal_add_expected_type_urls() {
  return expected_type_urls_.Add();
}
inline void ExtendedExpression::add_expected_type_urls(const std::string& value) {
  expected_type_urls_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:substrait.proto.ExtendedExpression.expected_type_urls)
}
inline void ExtendedExpression::add_expected_type_urls(std::string&& value) {
  expected_type_urls_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:substrait.proto.ExtendedExpression.expected_type_urls)
}
inline void ExtendedExpression::add_expected_type_urls(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  expected_type_urls_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:substrait.proto.ExtendedExpression.expected_type_urls)
}
inline void ExtendedExpression::add_expected_type_urls(const char* value, size_t size) {
  expected_type_urls_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:substrait.proto.ExtendedExpression.expected_type_urls)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
ExtendedExpression::expected_type_urls() const {
  // @@protoc_insertion_point(field_list:substrait.proto.ExtendedExpression.expected_type_urls)
  return expected_type_urls_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
ExtendedExpression::mutable_expected_type_urls() {
  // @@protoc_insertion_point(field_mutable_list:substrait.proto.ExtendedExpression.expected_type_urls)
  return &expected_type_urls_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace substrait

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_substrait_2fproto_2fextended_5fexpression_2eproto
