// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: substrait/proto/plan.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_substrait_2fproto_2fplan_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_substrait_2fproto_2fplan_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "substrait/proto/algebra.pb.h"
#include "substrait/proto/extensions/extensions.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_substrait_2fproto_2fplan_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_substrait_2fproto_2fplan_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_substrait_2fproto_2fplan_2eproto;
namespace substrait {
namespace proto {
class Plan;
class PlanDefaultTypeInternal;
extern PlanDefaultTypeInternal _Plan_default_instance_;
class PlanRel;
class PlanRelDefaultTypeInternal;
extern PlanRelDefaultTypeInternal _PlanRel_default_instance_;
class PlanVersion;
class PlanVersionDefaultTypeInternal;
extern PlanVersionDefaultTypeInternal _PlanVersion_default_instance_;
class Version;
class VersionDefaultTypeInternal;
extern VersionDefaultTypeInternal _Version_default_instance_;
}  // namespace proto
}  // namespace substrait
PROTOBUF_NAMESPACE_OPEN
template<> ::substrait::proto::Plan* Arena::CreateMaybeMessage<::substrait::proto::Plan>(Arena*);
template<> ::substrait::proto::PlanRel* Arena::CreateMaybeMessage<::substrait::proto::PlanRel>(Arena*);
template<> ::substrait::proto::PlanVersion* Arena::CreateMaybeMessage<::substrait::proto::PlanVersion>(Arena*);
template<> ::substrait::proto::Version* Arena::CreateMaybeMessage<::substrait::proto::Version>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace substrait {
namespace proto {

// ===================================================================

class PlanRel PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:substrait.proto.PlanRel) */ {
 public:
  inline PlanRel() : PlanRel(nullptr) {};
  virtual ~PlanRel();

  PlanRel(const PlanRel& from);
  PlanRel(PlanRel&& from) noexcept
    : PlanRel() {
    *this = ::std::move(from);
  }

  inline PlanRel& operator=(const PlanRel& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlanRel& operator=(PlanRel&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PlanRel& default_instance();

  enum RelTypeCase {
    kRel = 1,
    kRoot = 2,
    REL_TYPE_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PlanRel* internal_default_instance() {
    return reinterpret_cast<const PlanRel*>(
               &_PlanRel_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PlanRel& a, PlanRel& b) {
    a.Swap(&b);
  }
  inline void Swap(PlanRel* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlanRel* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PlanRel* New() const final {
    return CreateMaybeMessage<PlanRel>(nullptr);
  }

  PlanRel* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PlanRel>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PlanRel& from);
  void MergeFrom(const PlanRel& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlanRel* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "substrait.proto.PlanRel";
  }
  protected:
  explicit PlanRel(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_substrait_2fproto_2fplan_2eproto);
    return ::descriptor_table_substrait_2fproto_2fplan_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRelFieldNumber = 1,
    kRootFieldNumber = 2,
  };
  // .substrait.proto.Rel rel = 1;
  bool has_rel() const;
  private:
  bool _internal_has_rel() const;
  public:
  void clear_rel();
  const ::substrait::proto::Rel& rel() const;
  ::substrait::proto::Rel* release_rel();
  ::substrait::proto::Rel* mutable_rel();
  void set_allocated_rel(::substrait::proto::Rel* rel);
  private:
  const ::substrait::proto::Rel& _internal_rel() const;
  ::substrait::proto::Rel* _internal_mutable_rel();
  public:
  void unsafe_arena_set_allocated_rel(
      ::substrait::proto::Rel* rel);
  ::substrait::proto::Rel* unsafe_arena_release_rel();

  // .substrait.proto.RelRoot root = 2;
  bool has_root() const;
  private:
  bool _internal_has_root() const;
  public:
  void clear_root();
  const ::substrait::proto::RelRoot& root() const;
  ::substrait::proto::RelRoot* release_root();
  ::substrait::proto::RelRoot* mutable_root();
  void set_allocated_root(::substrait::proto::RelRoot* root);
  private:
  const ::substrait::proto::RelRoot& _internal_root() const;
  ::substrait::proto::RelRoot* _internal_mutable_root();
  public:
  void unsafe_arena_set_allocated_root(
      ::substrait::proto::RelRoot* root);
  ::substrait::proto::RelRoot* unsafe_arena_release_root();

  void clear_rel_type();
  RelTypeCase rel_type_case() const;
  // @@protoc_insertion_point(class_scope:substrait.proto.PlanRel)
 private:
  class _Internal;
  void set_has_rel();
  void set_has_root();

  inline bool has_rel_type() const;
  inline void clear_has_rel_type();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  union RelTypeUnion {
    RelTypeUnion() {}
    ::substrait::proto::Rel* rel_;
    ::substrait::proto::RelRoot* root_;
  } rel_type_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_substrait_2fproto_2fplan_2eproto;
};
// -------------------------------------------------------------------

class Plan PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:substrait.proto.Plan) */ {
 public:
  inline Plan() : Plan(nullptr) {};
  virtual ~Plan();

  Plan(const Plan& from);
  Plan(Plan&& from) noexcept
    : Plan() {
    *this = ::std::move(from);
  }

  inline Plan& operator=(const Plan& from) {
    CopyFrom(from);
    return *this;
  }
  inline Plan& operator=(Plan&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Plan& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Plan* internal_default_instance() {
    return reinterpret_cast<const Plan*>(
               &_Plan_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Plan& a, Plan& b) {
    a.Swap(&b);
  }
  inline void Swap(Plan* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Plan* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Plan* New() const final {
    return CreateMaybeMessage<Plan>(nullptr);
  }

  Plan* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Plan>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Plan& from);
  void MergeFrom(const Plan& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Plan* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "substrait.proto.Plan";
  }
  protected:
  explicit Plan(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_substrait_2fproto_2fplan_2eproto);
    return ::descriptor_table_substrait_2fproto_2fplan_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kExtensionUrisFieldNumber = 1,
    kExtensionsFieldNumber = 2,
    kRelationsFieldNumber = 3,
    kExpectedTypeUrlsFieldNumber = 5,
    kAdvancedExtensionsFieldNumber = 4,
    kVersionFieldNumber = 6,
  };
  // repeated .substrait.proto.extensions.SimpleExtensionURI extension_uris = 1;
  int extension_uris_size() const;
  private:
  int _internal_extension_uris_size() const;
  public:
  void clear_extension_uris();
  ::substrait::proto::extensions::SimpleExtensionURI* mutable_extension_uris(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::extensions::SimpleExtensionURI >*
      mutable_extension_uris();
  private:
  const ::substrait::proto::extensions::SimpleExtensionURI& _internal_extension_uris(int index) const;
  ::substrait::proto::extensions::SimpleExtensionURI* _internal_add_extension_uris();
  public:
  const ::substrait::proto::extensions::SimpleExtensionURI& extension_uris(int index) const;
  ::substrait::proto::extensions::SimpleExtensionURI* add_extension_uris();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::extensions::SimpleExtensionURI >&
      extension_uris() const;

  // repeated .substrait.proto.extensions.SimpleExtensionDeclaration extensions = 2;
  int extensions_size() const;
  private:
  int _internal_extensions_size() const;
  public:
  void clear_extensions();
  ::substrait::proto::extensions::SimpleExtensionDeclaration* mutable_extensions(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::extensions::SimpleExtensionDeclaration >*
      mutable_extensions();
  private:
  const ::substrait::proto::extensions::SimpleExtensionDeclaration& _internal_extensions(int index) const;
  ::substrait::proto::extensions::SimpleExtensionDeclaration* _internal_add_extensions();
  public:
  const ::substrait::proto::extensions::SimpleExtensionDeclaration& extensions(int index) const;
  ::substrait::proto::extensions::SimpleExtensionDeclaration* add_extensions();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::extensions::SimpleExtensionDeclaration >&
      extensions() const;

  // repeated .substrait.proto.PlanRel relations = 3;
  int relations_size() const;
  private:
  int _internal_relations_size() const;
  public:
  void clear_relations();
  ::substrait::proto::PlanRel* mutable_relations(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::PlanRel >*
      mutable_relations();
  private:
  const ::substrait::proto::PlanRel& _internal_relations(int index) const;
  ::substrait::proto::PlanRel* _internal_add_relations();
  public:
  const ::substrait::proto::PlanRel& relations(int index) const;
  ::substrait::proto::PlanRel* add_relations();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::PlanRel >&
      relations() const;

  // repeated string expected_type_urls = 5;
  int expected_type_urls_size() const;
  private:
  int _internal_expected_type_urls_size() const;
  public:
  void clear_expected_type_urls();
  const std::string& expected_type_urls(int index) const;
  std::string* mutable_expected_type_urls(int index);
  void set_expected_type_urls(int index, const std::string& value);
  void set_expected_type_urls(int index, std::string&& value);
  void set_expected_type_urls(int index, const char* value);
  void set_expected_type_urls(int index, const char* value, size_t size);
  std::string* add_expected_type_urls();
  void add_expected_type_urls(const std::string& value);
  void add_expected_type_urls(std::string&& value);
  void add_expected_type_urls(const char* value);
  void add_expected_type_urls(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& expected_type_urls() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_expected_type_urls();
  private:
  const std::string& _internal_expected_type_urls(int index) const;
  std::string* _internal_add_expected_type_urls();
  public:

  // .substrait.proto.extensions.AdvancedExtension advanced_extensions = 4;
  bool has_advanced_extensions() const;
  private:
  bool _internal_has_advanced_extensions() const;
  public:
  void clear_advanced_extensions();
  const ::substrait::proto::extensions::AdvancedExtension& advanced_extensions() const;
  ::substrait::proto::extensions::AdvancedExtension* release_advanced_extensions();
  ::substrait::proto::extensions::AdvancedExtension* mutable_advanced_extensions();
  void set_allocated_advanced_extensions(::substrait::proto::extensions::AdvancedExtension* advanced_extensions);
  private:
  const ::substrait::proto::extensions::AdvancedExtension& _internal_advanced_extensions() const;
  ::substrait::proto::extensions::AdvancedExtension* _internal_mutable_advanced_extensions();
  public:
  void unsafe_arena_set_allocated_advanced_extensions(
      ::substrait::proto::extensions::AdvancedExtension* advanced_extensions);
  ::substrait::proto::extensions::AdvancedExtension* unsafe_arena_release_advanced_extensions();

  // .substrait.proto.Version version = 6;
  bool has_version() const;
  private:
  bool _internal_has_version() const;
  public:
  void clear_version();
  const ::substrait::proto::Version& version() const;
  ::substrait::proto::Version* release_version();
  ::substrait::proto::Version* mutable_version();
  void set_allocated_version(::substrait::proto::Version* version);
  private:
  const ::substrait::proto::Version& _internal_version() const;
  ::substrait::proto::Version* _internal_mutable_version();
  public:
  void unsafe_arena_set_allocated_version(
      ::substrait::proto::Version* version);
  ::substrait::proto::Version* unsafe_arena_release_version();

  // @@protoc_insertion_point(class_scope:substrait.proto.Plan)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::extensions::SimpleExtensionURI > extension_uris_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::extensions::SimpleExtensionDeclaration > extensions_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::PlanRel > relations_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> expected_type_urls_;
  ::substrait::proto::extensions::AdvancedExtension* advanced_extensions_;
  ::substrait::proto::Version* version_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_substrait_2fproto_2fplan_2eproto;
};
// -------------------------------------------------------------------

class PlanVersion PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:substrait.proto.PlanVersion) */ {
 public:
  inline PlanVersion() : PlanVersion(nullptr) {};
  virtual ~PlanVersion();

  PlanVersion(const PlanVersion& from);
  PlanVersion(PlanVersion&& from) noexcept
    : PlanVersion() {
    *this = ::std::move(from);
  }

  inline PlanVersion& operator=(const PlanVersion& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlanVersion& operator=(PlanVersion&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PlanVersion& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PlanVersion* internal_default_instance() {
    return reinterpret_cast<const PlanVersion*>(
               &_PlanVersion_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PlanVersion& a, PlanVersion& b) {
    a.Swap(&b);
  }
  inline void Swap(PlanVersion* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlanVersion* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PlanVersion* New() const final {
    return CreateMaybeMessage<PlanVersion>(nullptr);
  }

  PlanVersion* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PlanVersion>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PlanVersion& from);
  void MergeFrom(const PlanVersion& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlanVersion* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "substrait.proto.PlanVersion";
  }
  protected:
  explicit PlanVersion(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_substrait_2fproto_2fplan_2eproto);
    return ::descriptor_table_substrait_2fproto_2fplan_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVersionFieldNumber = 6,
  };
  // .substrait.proto.Version version = 6;
  bool has_version() const;
  private:
  bool _internal_has_version() const;
  public:
  void clear_version();
  const ::substrait::proto::Version& version() const;
  ::substrait::proto::Version* release_version();
  ::substrait::proto::Version* mutable_version();
  void set_allocated_version(::substrait::proto::Version* version);
  private:
  const ::substrait::proto::Version& _internal_version() const;
  ::substrait::proto::Version* _internal_mutable_version();
  public:
  void unsafe_arena_set_allocated_version(
      ::substrait::proto::Version* version);
  ::substrait::proto::Version* unsafe_arena_release_version();

  // @@protoc_insertion_point(class_scope:substrait.proto.PlanVersion)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::substrait::proto::Version* version_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_substrait_2fproto_2fplan_2eproto;
};
// -------------------------------------------------------------------

class Version PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:substrait.proto.Version) */ {
 public:
  inline Version() : Version(nullptr) {};
  virtual ~Version();

  Version(const Version& from);
  Version(Version&& from) noexcept
    : Version() {
    *this = ::std::move(from);
  }

  inline Version& operator=(const Version& from) {
    CopyFrom(from);
    return *this;
  }
  inline Version& operator=(Version&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Version& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Version* internal_default_instance() {
    return reinterpret_cast<const Version*>(
               &_Version_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Version& a, Version& b) {
    a.Swap(&b);
  }
  inline void Swap(Version* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Version* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Version* New() const final {
    return CreateMaybeMessage<Version>(nullptr);
  }

  Version* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Version>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Version& from);
  void MergeFrom(const Version& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Version* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "substrait.proto.Version";
  }
  protected:
  explicit Version(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_substrait_2fproto_2fplan_2eproto);
    return ::descriptor_table_substrait_2fproto_2fplan_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGitHashFieldNumber = 4,
    kProducerFieldNumber = 5,
    kMajorNumberFieldNumber = 1,
    kMinorNumberFieldNumber = 2,
    kPatchNumberFieldNumber = 3,
  };
  // string git_hash = 4;
  void clear_git_hash();
  const std::string& git_hash() const;
  void set_git_hash(const std::string& value);
  void set_git_hash(std::string&& value);
  void set_git_hash(const char* value);
  void set_git_hash(const char* value, size_t size);
  std::string* mutable_git_hash();
  std::string* release_git_hash();
  void set_allocated_git_hash(std::string* git_hash);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_git_hash();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_git_hash(
      std::string* git_hash);
  private:
  const std::string& _internal_git_hash() const;
  void _internal_set_git_hash(const std::string& value);
  std::string* _internal_mutable_git_hash();
  public:

  // string producer = 5;
  void clear_producer();
  const std::string& producer() const;
  void set_producer(const std::string& value);
  void set_producer(std::string&& value);
  void set_producer(const char* value);
  void set_producer(const char* value, size_t size);
  std::string* mutable_producer();
  std::string* release_producer();
  void set_allocated_producer(std::string* producer);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_producer();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_producer(
      std::string* producer);
  private:
  const std::string& _internal_producer() const;
  void _internal_set_producer(const std::string& value);
  std::string* _internal_mutable_producer();
  public:

  // uint32 major_number = 1;
  void clear_major_number();
  ::PROTOBUF_NAMESPACE_ID::uint32 major_number() const;
  void set_major_number(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_major_number() const;
  void _internal_set_major_number(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 minor_number = 2;
  void clear_minor_number();
  ::PROTOBUF_NAMESPACE_ID::uint32 minor_number() const;
  void set_minor_number(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_minor_number() const;
  void _internal_set_minor_number(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 patch_number = 3;
  void clear_patch_number();
  ::PROTOBUF_NAMESPACE_ID::uint32 patch_number() const;
  void set_patch_number(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_patch_number() const;
  void _internal_set_patch_number(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:substrait.proto.Version)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr git_hash_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr producer_;
  ::PROTOBUF_NAMESPACE_ID::uint32 major_number_;
  ::PROTOBUF_NAMESPACE_ID::uint32 minor_number_;
  ::PROTOBUF_NAMESPACE_ID::uint32 patch_number_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_substrait_2fproto_2fplan_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PlanRel

// .substrait.proto.Rel rel = 1;
inline bool PlanRel::_internal_has_rel() const {
  return rel_type_case() == kRel;
}
inline bool PlanRel::has_rel() const {
  return _internal_has_rel();
}
inline void PlanRel::set_has_rel() {
  _oneof_case_[0] = kRel;
}
inline ::substrait::proto::Rel* PlanRel::release_rel() {
  // @@protoc_insertion_point(field_release:substrait.proto.PlanRel.rel)
  if (_internal_has_rel()) {
    clear_has_rel_type();
      ::substrait::proto::Rel* temp = rel_type_.rel_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    rel_type_.rel_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::substrait::proto::Rel& PlanRel::_internal_rel() const {
  return _internal_has_rel()
      ? *rel_type_.rel_
      : *reinterpret_cast< ::substrait::proto::Rel*>(&::substrait::proto::_Rel_default_instance_);
}
inline const ::substrait::proto::Rel& PlanRel::rel() const {
  // @@protoc_insertion_point(field_get:substrait.proto.PlanRel.rel)
  return _internal_rel();
}
inline ::substrait::proto::Rel* PlanRel::unsafe_arena_release_rel() {
  // @@protoc_insertion_point(field_unsafe_arena_release:substrait.proto.PlanRel.rel)
  if (_internal_has_rel()) {
    clear_has_rel_type();
    ::substrait::proto::Rel* temp = rel_type_.rel_;
    rel_type_.rel_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void PlanRel::unsafe_arena_set_allocated_rel(::substrait::proto::Rel* rel) {
  clear_rel_type();
  if (rel) {
    set_has_rel();
    rel_type_.rel_ = rel;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:substrait.proto.PlanRel.rel)
}
inline ::substrait::proto::Rel* PlanRel::_internal_mutable_rel() {
  if (!_internal_has_rel()) {
    clear_rel_type();
    set_has_rel();
    rel_type_.rel_ = CreateMaybeMessage< ::substrait::proto::Rel >(GetArena());
  }
  return rel_type_.rel_;
}
inline ::substrait::proto::Rel* PlanRel::mutable_rel() {
  // @@protoc_insertion_point(field_mutable:substrait.proto.PlanRel.rel)
  return _internal_mutable_rel();
}

// .substrait.proto.RelRoot root = 2;
inline bool PlanRel::_internal_has_root() const {
  return rel_type_case() == kRoot;
}
inline bool PlanRel::has_root() const {
  return _internal_has_root();
}
inline void PlanRel::set_has_root() {
  _oneof_case_[0] = kRoot;
}
inline ::substrait::proto::RelRoot* PlanRel::release_root() {
  // @@protoc_insertion_point(field_release:substrait.proto.PlanRel.root)
  if (_internal_has_root()) {
    clear_has_rel_type();
      ::substrait::proto::RelRoot* temp = rel_type_.root_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    rel_type_.root_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::substrait::proto::RelRoot& PlanRel::_internal_root() const {
  return _internal_has_root()
      ? *rel_type_.root_
      : *reinterpret_cast< ::substrait::proto::RelRoot*>(&::substrait::proto::_RelRoot_default_instance_);
}
inline const ::substrait::proto::RelRoot& PlanRel::root() const {
  // @@protoc_insertion_point(field_get:substrait.proto.PlanRel.root)
  return _internal_root();
}
inline ::substrait::proto::RelRoot* PlanRel::unsafe_arena_release_root() {
  // @@protoc_insertion_point(field_unsafe_arena_release:substrait.proto.PlanRel.root)
  if (_internal_has_root()) {
    clear_has_rel_type();
    ::substrait::proto::RelRoot* temp = rel_type_.root_;
    rel_type_.root_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void PlanRel::unsafe_arena_set_allocated_root(::substrait::proto::RelRoot* root) {
  clear_rel_type();
  if (root) {
    set_has_root();
    rel_type_.root_ = root;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:substrait.proto.PlanRel.root)
}
inline ::substrait::proto::RelRoot* PlanRel::_internal_mutable_root() {
  if (!_internal_has_root()) {
    clear_rel_type();
    set_has_root();
    rel_type_.root_ = CreateMaybeMessage< ::substrait::proto::RelRoot >(GetArena());
  }
  return rel_type_.root_;
}
inline ::substrait::proto::RelRoot* PlanRel::mutable_root() {
  // @@protoc_insertion_point(field_mutable:substrait.proto.PlanRel.root)
  return _internal_mutable_root();
}

inline bool PlanRel::has_rel_type() const {
  return rel_type_case() != REL_TYPE_NOT_SET;
}
inline void PlanRel::clear_has_rel_type() {
  _oneof_case_[0] = REL_TYPE_NOT_SET;
}
inline PlanRel::RelTypeCase PlanRel::rel_type_case() const {
  return PlanRel::RelTypeCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// Plan

// .substrait.proto.Version version = 6;
inline bool Plan::_internal_has_version() const {
  return this != internal_default_instance() && version_ != nullptr;
}
inline bool Plan::has_version() const {
  return _internal_has_version();
}
inline void Plan::clear_version() {
  if (GetArena() == nullptr && version_ != nullptr) {
    delete version_;
  }
  version_ = nullptr;
}
inline const ::substrait::proto::Version& Plan::_internal_version() const {
  const ::substrait::proto::Version* p = version_;
  return p != nullptr ? *p : *reinterpret_cast<const ::substrait::proto::Version*>(
      &::substrait::proto::_Version_default_instance_);
}
inline const ::substrait::proto::Version& Plan::version() const {
  // @@protoc_insertion_point(field_get:substrait.proto.Plan.version)
  return _internal_version();
}
inline void Plan::unsafe_arena_set_allocated_version(
    ::substrait::proto::Version* version) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(version_);
  }
  version_ = version;
  if (version) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:substrait.proto.Plan.version)
}
inline ::substrait::proto::Version* Plan::release_version() {
  auto temp = unsafe_arena_release_version();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::substrait::proto::Version* Plan::unsafe_arena_release_version() {
  // @@protoc_insertion_point(field_release:substrait.proto.Plan.version)
  
  ::substrait::proto::Version* temp = version_;
  version_ = nullptr;
  return temp;
}
inline ::substrait::proto::Version* Plan::_internal_mutable_version() {
  
  if (version_ == nullptr) {
    auto* p = CreateMaybeMessage<::substrait::proto::Version>(GetArena());
    version_ = p;
  }
  return version_;
}
inline ::substrait::proto::Version* Plan::mutable_version() {
  // @@protoc_insertion_point(field_mutable:substrait.proto.Plan.version)
  return _internal_mutable_version();
}
inline void Plan::set_allocated_version(::substrait::proto::Version* version) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete version_;
  }
  if (version) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(version);
    if (message_arena != submessage_arena) {
      version = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, version, submessage_arena);
    }
    
  } else {
    
  }
  version_ = version;
  // @@protoc_insertion_point(field_set_allocated:substrait.proto.Plan.version)
}

// repeated .substrait.proto.extensions.SimpleExtensionURI extension_uris = 1;
inline int Plan::_internal_extension_uris_size() const {
  return extension_uris_.size();
}
inline int Plan::extension_uris_size() const {
  return _internal_extension_uris_size();
}
inline ::substrait::proto::extensions::SimpleExtensionURI* Plan::mutable_extension_uris(int index) {
  // @@protoc_insertion_point(field_mutable:substrait.proto.Plan.extension_uris)
  return extension_uris_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::extensions::SimpleExtensionURI >*
Plan::mutable_extension_uris() {
  // @@protoc_insertion_point(field_mutable_list:substrait.proto.Plan.extension_uris)
  return &extension_uris_;
}
inline const ::substrait::proto::extensions::SimpleExtensionURI& Plan::_internal_extension_uris(int index) const {
  return extension_uris_.Get(index);
}
inline const ::substrait::proto::extensions::SimpleExtensionURI& Plan::extension_uris(int index) const {
  // @@protoc_insertion_point(field_get:substrait.proto.Plan.extension_uris)
  return _internal_extension_uris(index);
}
inline ::substrait::proto::extensions::SimpleExtensionURI* Plan::_internal_add_extension_uris() {
  return extension_uris_.Add();
}
inline ::substrait::proto::extensions::SimpleExtensionURI* Plan::add_extension_uris() {
  // @@protoc_insertion_point(field_add:substrait.proto.Plan.extension_uris)
  return _internal_add_extension_uris();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::extensions::SimpleExtensionURI >&
Plan::extension_uris() const {
  // @@protoc_insertion_point(field_list:substrait.proto.Plan.extension_uris)
  return extension_uris_;
}

// repeated .substrait.proto.extensions.SimpleExtensionDeclaration extensions = 2;
inline int Plan::_internal_extensions_size() const {
  return extensions_.size();
}
inline int Plan::extensions_size() const {
  return _internal_extensions_size();
}
inline ::substrait::proto::extensions::SimpleExtensionDeclaration* Plan::mutable_extensions(int index) {
  // @@protoc_insertion_point(field_mutable:substrait.proto.Plan.extensions)
  return extensions_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::extensions::SimpleExtensionDeclaration >*
Plan::mutable_extensions() {
  // @@protoc_insertion_point(field_mutable_list:substrait.proto.Plan.extensions)
  return &extensions_;
}
inline const ::substrait::proto::extensions::SimpleExtensionDeclaration& Plan::_internal_extensions(int index) const {
  return extensions_.Get(index);
}
inline const ::substrait::proto::extensions::SimpleExtensionDeclaration& Plan::extensions(int index) const {
  // @@protoc_insertion_point(field_get:substrait.proto.Plan.extensions)
  return _internal_extensions(index);
}
inline ::substrait::proto::extensions::SimpleExtensionDeclaration* Plan::_internal_add_extensions() {
  return extensions_.Add();
}
inline ::substrait::proto::extensions::SimpleExtensionDeclaration* Plan::add_extensions() {
  // @@protoc_insertion_point(field_add:substrait.proto.Plan.extensions)
  return _internal_add_extensions();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::extensions::SimpleExtensionDeclaration >&
Plan::extensions() const {
  // @@protoc_insertion_point(field_list:substrait.proto.Plan.extensions)
  return extensions_;
}

// repeated .substrait.proto.PlanRel relations = 3;
inline int Plan::_internal_relations_size() const {
  return relations_.size();
}
inline int Plan::relations_size() const {
  return _internal_relations_size();
}
inline void Plan::clear_relations() {
  relations_.Clear();
}
inline ::substrait::proto::PlanRel* Plan::mutable_relations(int index) {
  // @@protoc_insertion_point(field_mutable:substrait.proto.Plan.relations)
  return relations_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::PlanRel >*
Plan::mutable_relations() {
  // @@protoc_insertion_point(field_mutable_list:substrait.proto.Plan.relations)
  return &relations_;
}
inline const ::substrait::proto::PlanRel& Plan::_internal_relations(int index) const {
  return relations_.Get(index);
}
inline const ::substrait::proto::PlanRel& Plan::relations(int index) const {
  // @@protoc_insertion_point(field_get:substrait.proto.Plan.relations)
  return _internal_relations(index);
}
inline ::substrait::proto::PlanRel* Plan::_internal_add_relations() {
  return relations_.Add();
}
inline ::substrait::proto::PlanRel* Plan::add_relations() {
  // @@protoc_insertion_point(field_add:substrait.proto.Plan.relations)
  return _internal_add_relations();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::substrait::proto::PlanRel >&
Plan::relations() const {
  // @@protoc_insertion_point(field_list:substrait.proto.Plan.relations)
  return relations_;
}

// .substrait.proto.extensions.AdvancedExtension advanced_extensions = 4;
inline bool Plan::_internal_has_advanced_extensions() const {
  return this != internal_default_instance() && advanced_extensions_ != nullptr;
}
inline bool Plan::has_advanced_extensions() const {
  return _internal_has_advanced_extensions();
}
inline const ::substrait::proto::extensions::AdvancedExtension& Plan::_internal_advanced_extensions() const {
  const ::substrait::proto::extensions::AdvancedExtension* p = advanced_extensions_;
  return p != nullptr ? *p : *reinterpret_cast<const ::substrait::proto::extensions::AdvancedExtension*>(
      &::substrait::proto::extensions::_AdvancedExtension_default_instance_);
}
inline const ::substrait::proto::extensions::AdvancedExtension& Plan::advanced_extensions() const {
  // @@protoc_insertion_point(field_get:substrait.proto.Plan.advanced_extensions)
  return _internal_advanced_extensions();
}
inline void Plan::unsafe_arena_set_allocated_advanced_extensions(
    ::substrait::proto::extensions::AdvancedExtension* advanced_extensions) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(advanced_extensions_);
  }
  advanced_extensions_ = advanced_extensions;
  if (advanced_extensions) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:substrait.proto.Plan.advanced_extensions)
}
inline ::substrait::proto::extensions::AdvancedExtension* Plan::release_advanced_extensions() {
  auto temp = unsafe_arena_release_advanced_extensions();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::substrait::proto::extensions::AdvancedExtension* Plan::unsafe_arena_release_advanced_extensions() {
  // @@protoc_insertion_point(field_release:substrait.proto.Plan.advanced_extensions)
  
  ::substrait::proto::extensions::AdvancedExtension* temp = advanced_extensions_;
  advanced_extensions_ = nullptr;
  return temp;
}
inline ::substrait::proto::extensions::AdvancedExtension* Plan::_internal_mutable_advanced_extensions() {
  
  if (advanced_extensions_ == nullptr) {
    auto* p = CreateMaybeMessage<::substrait::proto::extensions::AdvancedExtension>(GetArena());
    advanced_extensions_ = p;
  }
  return advanced_extensions_;
}
inline ::substrait::proto::extensions::AdvancedExtension* Plan::mutable_advanced_extensions() {
  // @@protoc_insertion_point(field_mutable:substrait.proto.Plan.advanced_extensions)
  return _internal_mutable_advanced_extensions();
}
inline void Plan::set_allocated_advanced_extensions(::substrait::proto::extensions::AdvancedExtension* advanced_extensions) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(advanced_extensions_);
  }
  if (advanced_extensions) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(advanced_extensions)->GetArena();
    if (message_arena != submessage_arena) {
      advanced_extensions = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, advanced_extensions, submessage_arena);
    }
    
  } else {
    
  }
  advanced_extensions_ = advanced_extensions;
  // @@protoc_insertion_point(field_set_allocated:substrait.proto.Plan.advanced_extensions)
}

// repeated string expected_type_urls = 5;
inline int Plan::_internal_expected_type_urls_size() const {
  return expected_type_urls_.size();
}
inline int Plan::expected_type_urls_size() const {
  return _internal_expected_type_urls_size();
}
inline void Plan::clear_expected_type_urls() {
  expected_type_urls_.Clear();
}
inline std::string* Plan::add_expected_type_urls() {
  // @@protoc_insertion_point(field_add_mutable:substrait.proto.Plan.expected_type_urls)
  return _internal_add_expected_type_urls();
}
inline const std::string& Plan::_internal_expected_type_urls(int index) const {
  return expected_type_urls_.Get(index);
}
inline const std::string& Plan::expected_type_urls(int index) const {
  // @@protoc_insertion_point(field_get:substrait.proto.Plan.expected_type_urls)
  return _internal_expected_type_urls(index);
}
inline std::string* Plan::mutable_expected_type_urls(int index) {
  // @@protoc_insertion_point(field_mutable:substrait.proto.Plan.expected_type_urls)
  return expected_type_urls_.Mutable(index);
}
inline void Plan::set_expected_type_urls(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:substrait.proto.Plan.expected_type_urls)
  expected_type_urls_.Mutable(index)->assign(value);
}
inline void Plan::set_expected_type_urls(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:substrait.proto.Plan.expected_type_urls)
  expected_type_urls_.Mutable(index)->assign(std::move(value));
}
inline void Plan::set_expected_type_urls(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  expected_type_urls_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:substrait.proto.Plan.expected_type_urls)
}
inline void Plan::set_expected_type_urls(int index, const char* value, size_t size) {
  expected_type_urls_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:substrait.proto.Plan.expected_type_urls)
}
inline std::string* Plan::_internal_add_expected_type_urls() {
  return expected_type_urls_.Add();
}
inline void Plan::add_expected_type_urls(const std::string& value) {
  expected_type_urls_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:substrait.proto.Plan.expected_type_urls)
}
inline void Plan::add_expected_type_urls(std::string&& value) {
  expected_type_urls_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:substrait.proto.Plan.expected_type_urls)
}
inline void Plan::add_expected_type_urls(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  expected_type_urls_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:substrait.proto.Plan.expected_type_urls)
}
inline void Plan::add_expected_type_urls(const char* value, size_t size) {
  expected_type_urls_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:substrait.proto.Plan.expected_type_urls)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Plan::expected_type_urls() const {
  // @@protoc_insertion_point(field_list:substrait.proto.Plan.expected_type_urls)
  return expected_type_urls_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Plan::mutable_expected_type_urls() {
  // @@protoc_insertion_point(field_mutable_list:substrait.proto.Plan.expected_type_urls)
  return &expected_type_urls_;
}

// -------------------------------------------------------------------

// PlanVersion

// .substrait.proto.Version version = 6;
inline bool PlanVersion::_internal_has_version() const {
  return this != internal_default_instance() && version_ != nullptr;
}
inline bool PlanVersion::has_version() const {
  return _internal_has_version();
}
inline void PlanVersion::clear_version() {
  if (GetArena() == nullptr && version_ != nullptr) {
    delete version_;
  }
  version_ = nullptr;
}
inline const ::substrait::proto::Version& PlanVersion::_internal_version() const {
  const ::substrait::proto::Version* p = version_;
  return p != nullptr ? *p : *reinterpret_cast<const ::substrait::proto::Version*>(
      &::substrait::proto::_Version_default_instance_);
}
inline const ::substrait::proto::Version& PlanVersion::version() const {
  // @@protoc_insertion_point(field_get:substrait.proto.PlanVersion.version)
  return _internal_version();
}
inline void PlanVersion::unsafe_arena_set_allocated_version(
    ::substrait::proto::Version* version) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(version_);
  }
  version_ = version;
  if (version) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:substrait.proto.PlanVersion.version)
}
inline ::substrait::proto::Version* PlanVersion::release_version() {
  auto temp = unsafe_arena_release_version();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::substrait::proto::Version* PlanVersion::unsafe_arena_release_version() {
  // @@protoc_insertion_point(field_release:substrait.proto.PlanVersion.version)
  
  ::substrait::proto::Version* temp = version_;
  version_ = nullptr;
  return temp;
}
inline ::substrait::proto::Version* PlanVersion::_internal_mutable_version() {
  
  if (version_ == nullptr) {
    auto* p = CreateMaybeMessage<::substrait::proto::Version>(GetArena());
    version_ = p;
  }
  return version_;
}
inline ::substrait::proto::Version* PlanVersion::mutable_version() {
  // @@protoc_insertion_point(field_mutable:substrait.proto.PlanVersion.version)
  return _internal_mutable_version();
}
inline void PlanVersion::set_allocated_version(::substrait::proto::Version* version) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete version_;
  }
  if (version) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(version);
    if (message_arena != submessage_arena) {
      version = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, version, submessage_arena);
    }
    
  } else {
    
  }
  version_ = version;
  // @@protoc_insertion_point(field_set_allocated:substrait.proto.PlanVersion.version)
}

// -------------------------------------------------------------------

// Version

// uint32 major_number = 1;
inline void Version::clear_major_number() {
  major_number_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Version::_internal_major_number() const {
  return major_number_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Version::major_number() const {
  // @@protoc_insertion_point(field_get:substrait.proto.Version.major_number)
  return _internal_major_number();
}
inline void Version::_internal_set_major_number(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  major_number_ = value;
}
inline void Version::set_major_number(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_major_number(value);
  // @@protoc_insertion_point(field_set:substrait.proto.Version.major_number)
}

// uint32 minor_number = 2;
inline void Version::clear_minor_number() {
  minor_number_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Version::_internal_minor_number() const {
  return minor_number_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Version::minor_number() const {
  // @@protoc_insertion_point(field_get:substrait.proto.Version.minor_number)
  return _internal_minor_number();
}
inline void Version::_internal_set_minor_number(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  minor_number_ = value;
}
inline void Version::set_minor_number(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_minor_number(value);
  // @@protoc_insertion_point(field_set:substrait.proto.Version.minor_number)
}

// uint32 patch_number = 3;
inline void Version::clear_patch_number() {
  patch_number_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Version::_internal_patch_number() const {
  return patch_number_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Version::patch_number() const {
  // @@protoc_insertion_point(field_get:substrait.proto.Version.patch_number)
  return _internal_patch_number();
}
inline void Version::_internal_set_patch_number(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  patch_number_ = value;
}
inline void Version::set_patch_number(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_patch_number(value);
  // @@protoc_insertion_point(field_set:substrait.proto.Version.patch_number)
}

// string git_hash = 4;
inline void Version::clear_git_hash() {
  git_hash_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Version::git_hash() const {
  // @@protoc_insertion_point(field_get:substrait.proto.Version.git_hash)
  return _internal_git_hash();
}
inline void Version::set_git_hash(const std::string& value) {
  _internal_set_git_hash(value);
  // @@protoc_insertion_point(field_set:substrait.proto.Version.git_hash)
}
inline std::string* Version::mutable_git_hash() {
  // @@protoc_insertion_point(field_mutable:substrait.proto.Version.git_hash)
  return _internal_mutable_git_hash();
}
inline const std::string& Version::_internal_git_hash() const {
  return git_hash_.Get();
}
inline void Version::_internal_set_git_hash(const std::string& value) {
  
  git_hash_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Version::set_git_hash(std::string&& value) {
  
  git_hash_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:substrait.proto.Version.git_hash)
}
inline void Version::set_git_hash(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  git_hash_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:substrait.proto.Version.git_hash)
}
inline void Version::set_git_hash(const char* value,
    size_t size) {
  
  git_hash_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:substrait.proto.Version.git_hash)
}
inline std::string* Version::_internal_mutable_git_hash() {
  
  return git_hash_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Version::release_git_hash() {
  // @@protoc_insertion_point(field_release:substrait.proto.Version.git_hash)
  return git_hash_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Version::set_allocated_git_hash(std::string* git_hash) {
  if (git_hash != nullptr) {
    
  } else {
    
  }
  git_hash_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), git_hash,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:substrait.proto.Version.git_hash)
}
inline std::string* Version::unsafe_arena_release_git_hash() {
  // @@protoc_insertion_point(field_unsafe_arena_release:substrait.proto.Version.git_hash)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return git_hash_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Version::unsafe_arena_set_allocated_git_hash(
    std::string* git_hash) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (git_hash != nullptr) {
    
  } else {
    
  }
  git_hash_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      git_hash, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:substrait.proto.Version.git_hash)
}

// string producer = 5;
inline void Version::clear_producer() {
  producer_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Version::producer() const {
  // @@protoc_insertion_point(field_get:substrait.proto.Version.producer)
  return _internal_producer();
}
inline void Version::set_producer(const std::string& value) {
  _internal_set_producer(value);
  // @@protoc_insertion_point(field_set:substrait.proto.Version.producer)
}
inline std::string* Version::mutable_producer() {
  // @@protoc_insertion_point(field_mutable:substrait.proto.Version.producer)
  return _internal_mutable_producer();
}
inline const std::string& Version::_internal_producer() const {
  return producer_.Get();
}
inline void Version::_internal_set_producer(const std::string& value) {
  
  producer_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Version::set_producer(std::string&& value) {
  
  producer_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:substrait.proto.Version.producer)
}
inline void Version::set_producer(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  producer_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:substrait.proto.Version.producer)
}
inline void Version::set_producer(const char* value,
    size_t size) {
  
  producer_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:substrait.proto.Version.producer)
}
inline std::string* Version::_internal_mutable_producer() {
  
  return producer_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Version::release_producer() {
  // @@protoc_insertion_point(field_release:substrait.proto.Version.producer)
  return producer_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Version::set_allocated_producer(std::string* producer) {
  if (producer != nullptr) {
    
  } else {
    
  }
  producer_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), producer,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:substrait.proto.Version.producer)
}
inline std::string* Version::unsafe_arena_release_producer() {
  // @@protoc_insertion_point(field_unsafe_arena_release:substrait.proto.Version.producer)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return producer_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Version::unsafe_arena_set_allocated_producer(
    std::string* producer) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (producer != nullptr) {
    
  } else {
    
  }
  producer_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      producer, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:substrait.proto.Version.producer)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace substrait

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_substrait_2fproto_2fplan_2eproto
